### ISSUE TITLE
カンマ、セミコロン、コロンの後ろには空白を入れる

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#15]
https://github.com/Genta-pvt/2023Portfolios/blob/707999444d6f2b5f2671b81c0e5d26e2c2ceeb9a/saitama_neko/SaitamaSeCats.py#L37-L38

配列も同様にいれましょう

**Comment by Genta-pvt** [comment]
直しました
`
        NORTHEAST_SET = {'northeast', 'NorthEast', 'Northeast', 'ne', 'NE', 'north', 'North', 'n', 'N'}
`
`
        SOUTHWEST_SET = {'southwest', 'SouthWest', 'Southwest', 'sw', 'SW', 'south', 'South', 's', 'S'}
`
