### ISSUE TITLE
演算子の前後に空白を入れる

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#16]
https://github.com/Genta-pvt/2023Portfolios/blob/707999444d6f2b5f2671b81c0e5d26e2c2ceeb9a/saitama_neko/SaitamaSeCats.py#L47

`&&`、`||`論理演算子や`&`、`|`ビット演算子も同様にいれます

**Comment by Genta-pvt** [comment]
直しました
`SaitamaCats.area = 'ne'`に
