### ISSUE TITLE
ignoreを設定。

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#2]
gitでプログラムや統合環境の設定ファイルをプッシュしないように設定します。
以下ワードで調べてみましょう。

```
git ignore
```

**Comment by Genta-pvt** [comment]
.gitignoreファイルを作って、設定。

### 詳細
1. ひとまず「状況.txt」を更新しないようにgitignore設定。  
2. すでにローカル環境でインデックスに登録してしまっていたので削除。
3. 状況.txtの内容を編集してからaddコマンドを実行し、インデックスに追加されないことを確認
