### ISSUE TITLE
=の前後に空白を入れる

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#30]
https://github.com/Genta-pvt/2023Portfolios/blob/12d6f350e171266ee88884402efb837aa6cc2179/saitama_neko/SaitamaSeCats.py#L61

__>NG__
```python
URL_SE= 'https://www.pref.saitama.lg.jp/b0716/joutoseineko-s.html'
```
***
__>OK__
```pyhton
URL_SE = 'https://www.pref.saitama.lg.jp/b0716/joutoseineko-s.html'
```

**Comment by Genta-pvt** [comment]
pycharmでリファクタリングしました
