### ISSUE TITLE
命名規則を変えましょう

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#4]
`saitama_se_cats.py`
`se_cats_schedule.py`
`test1.py`
`smtp_tst.py`
`smtptst2.py`
クラスの名前はキャメルケースに則って命名します。
詳しい命名規則はこちらを参照(https://python.softmoco.com/basics/python-naming-conventions.php)

**Comment by Genta-pvt** [comment]
`SaitamaSeCats.py`
`SeCatsSchedule.py`
`Test1.py`
`SmtpTst.py`
`Smtptst2.py`

に変更しました
