### ISSUE TITLE
空白を入れましょう

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#6]
https://github.com/Genta-pvt/2023Portfolios/blob/afd4449285225b9dd36f24323ba191e25342f751/saitama_neko/saitama_se_cats.py#L29
https://github.com/Genta-pvt/2023Portfolios/blob/afd4449285225b9dd36f24323ba191e25342f751/saitama_neko/saitama_se_cats.py#L42

変数や演算子の後には空白をいれて可読性を下げないように。

**Comment by Genta-pvt** [comment]
`    each_table = []`
`            if x := each_value.find_all('p'):`
としました
