### ISSUE TITLE
冗長な括弧の消去

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#7]
https://github.com/Genta-pvt/2023Portfolios/blob/afd4449285225b9dd36f24323ba191e25342f751/saitama_neko/saitama_se_cats.py#L55

returnのあとに変数を返すときには余分な括弧などを消しましょう。
可読性を下げる要因になります。

**Comment by Genta-pvt** [comment]
`    return message`
にしました
