### ISSUE TITLE
メソッドの間は2つ改行するようにする

### ISSUE THREAD

**Issue by koke9665** [Genta-pvt/2023Portfolios#9]
https://github.com/Genta-pvt/2023Portfolios/blob/afd4449285225b9dd36f24323ba191e25342f751/saitama_neko/saitama_se_cats.py#L23-L25
https://github.com/Genta-pvt/2023Portfolios/blob/afd4449285225b9dd36f24323ba191e25342f751/saitama_neko/saitama_se_cats.py#L55-L57

**Comment by Genta-pvt** [comment]
2行開けました
